version: '3.8'
services:
  db:
    image: postgres:16
    container_name: kiosco-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: kiosco
      POSTGRES_PASSWORD: kiosco
      POSTGRES_DB: kiosco
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    image: node:22
    container_name: kiosco-app
    restart: unless-stopped
    network_mode: host # Use host network
    # ports: # Not needed with network_mode: host
    #   - "3000:3000"
    working_dir: /app # Set working directory for consistency
    volumes:
      # Mount the ./kiosco subdirectory (relative to this docker-compose.yml) to /app
      - ./kiosco:/app
      # Use a named volume for node_modules to prevent host's node_modules from overwriting the container's
      - app_node_modules:/app/node_modules
      # Similarly, keep .next directory in a volume
      - app_next:/app/.next
    depends_on:
      - db
    command: npm run dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL="postgresql://kiosco:kiosco@localhost:5432/kiosco"
      - JWT_SECRET="tararira"
volumes:
  db_data:
  app_node_modules:
  app_next:
